name: Build & Deploy Info Football

on:
  push:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io/nawfalrakhmansah
  IMAGE_NAME: info-football
  GH_REGISTRY: ghcr.io

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          registry: ${{ env.GH_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: deployaja/deployaja-cli@v0.0.15
        with:
          command: plan
          api-token: ${{ secrets.DEPLOYAJA_TOKEN }}

      - uses: deployaja/deployaja-cli@v0.0.15
        with:
          command: deploy
          api-token: ${{ secrets.DEPLOYAJA_TOKEN }}
          additional-args: --set container.image=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          docker-registry: ${{ env.GH_REGISTRY }}
          docker-username: ${{ secrets.USERNAME }}
          docker-password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
