name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: DeployAja Plan
        uses: deployaja/deployaja-cli@v0.0.15
        with:
          command: plan
          api-token: ${{ secrets.DEPLOYAJA_TOKEN }}
          config-file: deployaja.yml   # ⬅️ INI DOANG

      - name: DeployAja Deploy
        uses: deployaja/deployaja-cli@v0.0.15
        with:
          command: deploy
          api-token: ${{ secrets.DEPLOYAJA_TOKEN }}
          config-file: deployaja.yml   # ⬅️ INI DOANG
          docker-registry: ghcr.io
          docker-username: ${{ github.actor }}
          docker-password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
