name: Docker Build and Publish and Deploy to DeployAja

on:
  push:
    branches: ["main"]

env:
  REGISTRY: ghcr.io/nawfalrakhmansah
  IMAGE_NAME: info-football
  GH_REGISTRY: ghcr.io
  DOCKER_BUILDKIT: 1

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

      - name: Build and push image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: DeployAja Plan
        uses: deployaja/deployaja-cli@v0.0.10
        with:
          command: plan
          config-file: deployaja.yml
        env:
          DEPLOYAJA_TOKEN: ${{ secrets.DEPLOYAJA_TOKEN }}

      - name: DeployAja Deploy
        uses: deployaja/deployaja-cli@v0.0.10
        with:
          command: deploy
          config-file: deployaja.yml
          additional-args: --set container.image=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
        env:
          DEPLOYAJA_TOKEN: ${{ secrets.DEPLOYAJA_TOKEN }}

      - name: DeployAja Status
        uses: deployaja/deployaja-cli@v0.0.10
        with:
          command: status
          config-file: deployaja.yml
        env:
          DEPLOYAJA_TOKEN: ${{ secrets.DEPLOYAJA_TOKEN }}
