- name: DeployAja Plan
  uses: deployaja/deployaja-cli@v0.0.15
  with:
    command: plan
    config-file: deployaja.yml
  env:
    DEPLOYAJA_TOKEN: ${{ secrets.DEPLOYAJA_TOKEN }}

- name: DeployAja Deploy
  uses: deployaja/deployaja-cli@v0.0.15
  with:
    command: deploy
    config-file: deployaja.yml
    docker-registry: ghcr.io
    docker-username: ${{ github.actor }}
    docker-password: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  env:
    DEPLOYAJA_TOKEN: ${{ secrets.DEPLOYAJA_TOKEN }}
